version: "3"
services:
  zookeeper:
    image: zookeeper

  kafka:
    image: eitanya/kafka:0.11.0.2
    ports:
      - 9092
    environment:
      KAFKA_LOG_CLEANUP_POLICY: "compact"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 20000
      KAFKA_LOG_SEGMENT_BYTES: 512000
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 16000
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 16000
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 10000

  consumer:
    build:
      context: ./
      dockerfile: Dockerfile.consumer
    image: consumer:1.0
    environment:
      group.id: weather-group
      bootstrap.servers: kafka:9092
      TOPIC: weather_topic
    restart: unless-stopped
    depends_on:
      - kafka

  producer:
    build:
      context: ./
      dockerfile: Dockerfile.producer
    image: producer:1.0
    environment:
      bootstrap.servers: kafka:9092
      TOPIC: weather_topic
    restart: unless-stopped
    depends_on:
      - kafka
